name: 'Terraform Plan'

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan
      continue-on-error: true

    - name: Terraform Show
      id: show
      run: terraform show -no-color tfplan > plan.txt

    - name: Upload Plan as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: ./infra/plan.txt
        retention-days: 5

    - name: Add Plan to PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('./infra/plan.txt', 'utf8');
          const MAX_COMMENT_SIZE = 65536;
          let planSummary = plan.length > MAX_COMMENT_SIZE 
            ? plan.substring(0, MAX_COMMENT_SIZE) + '\n\n... (Output truncated, see attached plan artifact for complete plan)'
            : plan;
          
          const comment = `## Terraform Plan 📝\n
          \`\`\`terraform\n
          ${planSummary}
          \`\`\`\n
          *Pusher: @${context.payload.pull_request.user.login}, Action: ${context.eventName}*`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          })